### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by maysam** [robocopkaka/stock_bearer_app#6]
Did you get to the next round of interview with this code?

**Comment by robocopkaka** [comment]
Yeah, I did.

**Comment by maysam** [comment]
what happened then? did you get an offer? :D

**Comment by robocopkaka** [comment]
I didn't get an offer. Had a technical interview which I was told I did well in but they didn't move forward with me for some other reason.

**Comment by maysam** [comment]
Thank you :)
